jobs:
  include:
    -stage: test
    language: python
    python:
      - "3.6"
      - "3.7"
      - "3.8"
      - "nightly"
    install: pip3 install -r requirements-dev.txt
    script: pytest --verbose